2023-01-13 15:28:01,236:ERROR:multiModel.py:featureImportance:Something went wrong with feature importance plot
Traceback (most recent call last):
  File "D:\Documents\mato\OneDrive - BRGM\Bureau\Aleasismique_Mayotte\Code\Application_EDA\dash_app\classes_py\multiModel.py", line 199, in featureImportance
    rf = RandomForestRegressor(n_estimators=100)
NameError: name 'RandomForestRegressor' is not defined
2023-01-13 15:30:28,452:ERROR:multiModel.py:featureImportance:Something went wrong with feature importance plot
Traceback (most recent call last):
  File "D:\Documents\mato\OneDrive - BRGM\Bureau\Aleasismique_Mayotte\Code\Application_EDA\dash_app\classes_py\multiModel.py", line 199, in featureImportance
    rf = RandomForestRegressor(n_estimators=100)
NameError: name 'RandomForestRegressor' is not defined
2023-01-13 16:02:49,857:INFO:dash.py:run:Dash is running on http://127.0.0.1:8080/

2023-01-13 16:34:21,923:INFO:dash.py:run:Dash is running on http://127.0.0.1:8080/

2023-01-13 16:46:23,403:INFO:dash.py:run:Dash is running on http://127.0.0.1:8080/

